# Gpu配置
GPU:
  use: True
  id:   1

# 模型配置
STG:
  num_class:        2
  normal_channel:   True
  npoints:          162 # 点集个数
  nblocks:          7  # transformer个数
  nneighbor:        16
  n_c:              40 # 分类
  d_points:         4  # 点维度，包括位置xyz和特征
  out_dim:          1024

  sts_dim:          128
  stg_dim:          64

  in_dim_node:      1  # node_dim (feat is an integer)
  hidden_dim:       80
  out_dim_g:        80
  n_classes:        2
  num_heads:        8
  in_feat_dropout:  0.0
  dropout:          0.0
  n_layers:         10
  datasetname:      "SAR-Change"
  readout:          "mean"
  layer_norm:       False
  batch_norm:       False
  self_loop:        False
  lap_pos_enc:      False
  wl_pos_enc:       False
  full_graph:       False
  residual:         True
  causal_k:       4

# 训练配置
Train:
  epochs:                15
  batchsize:             16
  n_worker:              4         # 加载数据（batch）的线程数目
  lr:                    0.001     # 学习率
  resume:                ''        # 加载预训练权重的文件
  T_0:                   5         # 优化器参数
  T_mult:                2         # 优化器参数
  finetune_train_ratio:  0.2       #finetune训练集比例
  finetune:             'checkpoints/'
  best_path:            'checkpoints/'
  final_model:          'checkpoints/best0_32-pseudo_causal.pkl'
# 训练数据配置
Data:
  root:  'datasets/'
  split:  0.3
